TykTechnologies/tyk-sync

vendor/github.com/xanzy/ssh-agent/pageant_windows.go, vendor/vendor.json
@letzya reported a similar issue (from another project, [here](https://github.com/jfrog/jfrog-cli-go/issues/205)). Seems that updating ssh-agent fixes the compatibility with newer Go versions in Windows builds.
=> Update ssh-agent package

README.md, cmd/argchecker.go, cmd/publish.go, cmd/shared.go, cmd/sync.go, cmd/update.go, tyk-vcs/getter.go, tyk-vcs/getter_test.go
- adds a new command line argument to read definition files from any
directory on the local file system
- introduces a Getter interface with both  a Git and a file system
implementation
- centralizes duplicated cli argument verification
- extracts publisher from getter for clearer separation of concerns
=> Allows local file system to be used as source, fixes #6

clients/gateway/certs.go
Reference: https://github.com/TykTechnologies/tyk-sync/issues/15
The gateway expects "X-Tyk-Authorization" header instead of "Authorization". This should not impact communication with the dashboard since it has its own certs.go file
=> Fixed authorization header for gateway

clients/dashboard/apis.go, clients/dashboard/policies.go, clients/objects/policies.go
Issue: #25 
This PR tries to solve the problem generated when we try to sync APIs with associated Policies. 
This is mainly caused by a bug when we try to retain the api_id of the API and its relation with the policy access rights.
Also, when the API has OIDC configured you have to update the policy associated with it since it has changed.
=> APIs with associated Policies synced are not working

.github/actions/packagecloud/Dockerfile, .github/actions/packagecloud/README.md, .github/actions/packagecloud/action.yml, .github/actions/packagecloud/pc-wrapper.sh, .github/workflows/unstable-packages.yml, .gitignore, .goreleaser.yml
Builds packages for i386, arm64 (v7) and amd64. Building both arm64 and arm breaks RPM uploads so it is a minimal set right now.
See a run of the workflow at https://github.com/TykTechnologies/tyk-sync/runs/830425742?check_suite_focus=true
See packages at https://packagecloud.io/tyk/tyk-sync-unstable
=> Add auto-build of packages on pushes to master

clients/dashboard/apis.go, cmd/dump.go, cmd/publish.go, cmd/shared.go, cmd/sync.go, cmd/update.go
**Removed the -a and -p** shortcuts and now it only accepts **`--apis` and `--policies`.** for selection. 
**Change the dump selection behavior:**
- If one or more APIs are selected, dump those APIs.
- If one or more Policies are selected, dump those Policies.
- If neither Policies nor APIs is specified, dump everything.
For example:
```
dump --apis="api_id_1" <- dumps only the API 1
dump --policies="pol_1" <- dumps only the POL 1
dump --apis="api_id_1"  --policies="pol_1"  <- dumps API 1 and POL 1
dump <- dump everything
```
Extended the selection support to **sync, publish, and update** commands.
=> [TT-309] Feature/selection

cli-publisher/dashboard.go, cli-publisher/gateway.go, cli-publisher/mock.go, clients/dashboard/apis.go, clients/gateway/client.go, clients/interfaces/client.go, clients/objects/apidef.go, cmd/dump.go, cmd/shared.go, tyk-swagger/swagger.go, tyk-vcs/getter.go, tyk-vcs/publisher.go
Update and replace of `apidef.APIDefinition` for `objects.DBApiDefinition`since the dashboard uses the second one.
Also added a  backward-compatible way to parse the old dumps.
Tested using sync with an old dump file.
Tested dumping a new file and syncing again.
Tested using sync with a gateway only (without dashboard).
=> [TT-482] Update Apidef struct

cmd/dump.go
Fix a bug that was introduced in 6b36e91270a9c287c40c93a1e1f6c3de409a9bd2
=> [TT-1093] Ensure nested API definition object is initialized when using dump command

clients/dashboard/apis.go
Changing UpdateAPI object to do the PUT and don't lose ownership data when we update an API (or we try to retain ID's).
Retain the ownership data with publish, sync and update.
1- create API with Ownership 
2- dump the API
3- Delete the API from the dashboard.
4- tyk-sync publish / sync the dump.
5- Check in the dashboard if the ownership is still there.
=> [TT-482]Change UpdateAPI object 

cmd/version.go
This PR adds a version command that prints the current tyk-sync version.
Usage:
`tyk-sync version`
Help:
`tyk-sync help` will show version as an available command with it's corresponding description.
Motivation:
https://tyktech.atlassian.net/browse/TT-889
=> TT-889  Version command

clients/dashboard/apis.go, clients/gateway/client.go, clients/objects/apidef.go, cmd/dump.go, go.mod, tyk-swagger/swagger.go, tyk-vcs/getter.go
This PR drops the import github.com/clarketm/json lib since it needs go 1.17 to run and we're on 1.15 here.
To avoid the marshaling of new struct fields in dumps, I switched to an internal APIdef struct and override those new struct fields as a `*Struct`.
In that way, when using tyk-sync in older Tyk versions, those new fields are just not marshaled since the dashboard API don't contain them.
=> TT-5555 Different approach for future compatibility

.github/dependabot.yml
The team name in GH changed from platform to platform-squad, then updated the dependabot file to pint to a valid name of group of reviewers
=> updated the reviewers group in dependabot

clients/dashboard/apis.go, clients/gateway/client.go, clients/objects/apidef.go, cmd/version.go
Fix/backwards apidef (#95)
* using accept_additional_properties when creating APIs
* bumping version
* adding additional_params to update call
* adding additional_params to update call
* adding second backwards compatibility layer around external_oauth
* adding omitempty to external_oauth
=> Merging to release-1.2: Fix/backwards apidef (#95)

clients/examplesrepo/client.go, clients/examplesrepo/client_test.go, clients/examplesrepo/models.go, clients/examplesrepo/utils.go, clients/examplesrepo/utils_test.go, cmd/examples.go, cmd/shared.go, go.mod, go.sum
This PR adds a new command `examples` which will retrieve all official examples from `tyk-examples` repository at GitHub.
The output looks like this:
```
LOCATION            NAME                DESCRIPTION
udg/first-demo      First UDG Demo      This UDG demo is very simple
udg/complex-demo    Complex UDG Demo    This UDG demo is very complex
```
=> add new examples command (TT-7409)

clients/examplesrepo/client.go, cmd/examples_publish.go, cmd/shared.go, tyk-vcs/getter.go, tyk-vcs/getter_test.go
This PR adds the new command `examples publish` which can be used to publish a specific example from a subdirectory to dashboard or API (it uses the same `publish` code).
Usage:
```
tyk-sync examples publish -d=http://localhost:3000 -s=secret -l=udg/first-demo
```
or with optional git repository URL:
```
tyk-sync examples publish -d=http://localhost:3000 -s=secret -l=udg/first-demo https://github.com/pvormste/tyk-examples.git
```
Output (example):
```
Fetched 1 definitions
Fetched 0 policies
Using publisher: Dashboard Publisher
org override detected, setting.
Creating API 0: sync-countries
--> Status: OK, ID:d86db3f61a3b465376823cf22d393343
Updating API 0: sync-countries
--> Status: OK, ID:d86db3f61a3b465376823cf22d393343
org override detected, setting.
Done
```
=> add examples publish command

README.md
This PR adds a short section on how to use `tyk-sync examples` to the README.
=> add examples usage section to readme (TT-8179)

clients/dashboard/apis.go, clients/dashboard/policies.go, clients/gateway/client.go, go.mod, go.sum, tyk-swagger/swagger.go
This PR fix critical CVE https://dso.docker.com/cve/CVE-2021-3538 dropping `staori/go.uuid` dependency.
It also updates Tyk Gateway to latest `release-5.0` branch since that dependency was also solved there.
unstable created from this branch:
https://tyktech.atlassian.net/browse/TT-8480
=> TT-8480 Fix uuid CVE

.github/workflows/release.yml
nfpmreplacements have been removed in latest version
https://goreleaser.com/deprecations/#nfpmsreplacements
pin 1.18 for now, address update later
https://tyktech.atlassian.net/browse/TT-9292
=> TT-9292 Latest goreleaser has breaking change in replacements, pin 1.18

clients/dashboard/apis.go, clients/dashboard/client.go
When API update operation is made by `tyk-sync`, it uses oas api update endpoint of `tyk-analytics` which doesn't respect some features that are not yet available in OAS. So, it should use classic api definition format to cover all features.
This requires the dashboard classic API endpoint to accept `"is_oas": true` payloads. That will be handled with this PR: https://github.com/TykTechnologies/tyk-analytics/pull/3384
Parent: https://tyktech.atlassian.net/browse/TT-9628
Subtask: https://tyktech.atlassian.net/browse/TT-9718
=> [TT-9628/TT-9718] Disable OAS update endpoint usage, use classic endpoint instead

cli-publisher/dashboard.go, clients/dashboard/apis.go, clients/dashboard/client.go, cmd/dump.go, cmd/publish.go, cmd/shared.go, cmd/sync.go, cmd/update.go
This PR adds `--allow-unsafe-oas` flag to `update`, `sync` and `publish` commands so that if it is set, it will stop using `oas` API update endpoint in the dashboard. It will use classic API update endpoints instead.
=> [TT-10190] Add allow-unsafe-oas flag

cmd/version.go
TT-10421 Update 1.4.2 version (#127)
=> Merging to release-1.4: TT-10421 Update 1.4.2 version (#127)

cli-publisher/dashboard.go, clients/dashboard/apis.go, clients/dashboard/client.go, clients/objects/apidef.go, cmd/dump.go, tyk-vcs/getter.go
Allow users to dump OAS APIs by using dump command.
Integrate new OAS API endpoints to Tyk Sync to make it work with OAS APIs. So that users can dump their Tyk installation without providing any additional configuration flags such as --allow-unsafe-oas and OAS can be dumped in a fully functional way including categories.
Internal ticket: https://tyktech.atlassian.net/browse/TT-11743
=> [TT-11743] - Tyk Sync OAS Support: dump command

.github/workflows/linter.yaml, clients/dashboard/apis.go, clients/dashboard/client.go, cmd/dump.go, cmd/sync.go, tyk-vcs/getter.go
- Deprecated `allow-unsafe-oas` flag of sync command.
- Added workflow for running linter
[TT-11744](https://tyktech.atlassian.net/browse/TT-11744)
[TT-11744]: https://tyktech.atlassian.net/browse/TT-11744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [TT-11744] Deprecate `allow-unsafe-oas` flag of sync command

cmd/publish.go, cmd/sync.go, cmd/update.go
Deprecated allow-unsafe-oas flag of update and publish command.
[TT-11745](https://tyktech.atlassian.net/browse/TT-11745)
[TT-11745]: https://tyktech.atlassian.net/browse/TT-11745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [TT-11745] Deprecate --allow-unsafe-oas flag of update and publish command

.gitignore, cli-publisher/dashboard.go, cli-publisher/gateway.go, cli-publisher/mock.go, clients/dashboard/assets.go, clients/dashboard/client.go, clients/gateway/client.go, clients/objects/assets.go, cmd/dump.go, cmd/publish.go, cmd/shared.go, cmd/sync.go, cmd/update.go, main.go, tyk-vcs/getter.go, tyk-vcs/publisher.go, tyk-vcs/spec.go
```
change implements Tyk Sync commands (dump, publish, sync, update) for API Template
```
https://tyktech.atlassian.net/browse/TT-11491
=> TT-11491: implement sync commands for API Template

clients/gateway/client.go
tyk-sync update is not working as expected because of extra / at the end of endpoint. Due to this PUT calls were going GET and its giving 200 ok response but actual update is not happening
=> TT-12006 remove / at the end on update api

clients/examplesrepo/client_test.go, clients/examplesrepo/models.go, clients/examplesrepo/utils.go, clients/examplesrepo/utils_test.go
This PR fixes an issue where the category have been hard coded and would not pick up new categories dynamcially
=> make examples categories dynamic
